### ISSUE TITLE
json_decode() expects parameter 1 to be string, bool given

### ISSUE THREAD

**Issue by webmake** [hipay/hipay-fullservice-sdk-php#45] opened 2019-09-04 09:00 UTC
Since we updated library, this error occured within `SimpleHTTPClient` class
```
json_decode() expects parameter 1 to be string, bool given
```
https://github.com/hipay/hipay-fullservice-sdk-php/blob/ee70b35512574720eb2491d187db19a730560b30/lib/HiPay/Fullservice/HTTP/SimpleHTTPClient.php#L132
because of
```
        if ((false === $result) && !$isData) {
            throw new CurlException(curl_error($this->_httpClient), curl_errno($this->_httpClient));
        }
```
when `PIDataClient` asserts that `sendData` never fails with curl errors

**Comment by etiennelandais** [comment] 2019-09-04 12:49
Hello, 

I understand where the error come from but I can't reproduce it on my environment.

What's your PHP setup (version, configuration, framework, etc) ? 

I've a fix in mind but I want to be sure and for that I need to able to reproduce the error

Regards

**Comment by webmake** [comment] 2019-09-05 06:57
You can turn off internet temporary, and this is how error can be reproduced

**Comment by etiennelandais** [comment] 2019-09-06 09:05
this issue has been fixed in the latest release 

https://github.com/hipay/hipay-fullservice-sdk-php/releases/tag/2.3.1

Thank you for your contribution

Regards

**Closed by etiennelandais** 2019-09-06 09:05 UTC
